# **1. Data Manipulation**

## **1.1. Getting Started**

In [2]:
import numpy as np

In [3]:
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape

(12,)

In [5]:
x.size

12

In [7]:
x = x.reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
np.empty((3, 4))

array([[4.66245962e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [9]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [11]:
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [12]:
np.random.normal(0, 1, size=(3, 4))

array([[ 0.08932058,  0.20945218, -1.33814919, -0.33771239],
       [ 0.26824117,  0.97142924,  0.35987092,  0.499379  ],
       [ 0.21736773,  1.2738983 , -0.24803851, -0.87749558]])

In [13]:
np.array([[2, 1, 3, 4], [1, 3, 4, 2], [4, 3, 1, 2]])

array([[2, 1, 3, 4],
       [1, 3, 4, 2],
       [4, 3, 1, 2]])

## **1.2. Operators**

In [14]:
x = np.array([1, 2, 4, 8])
y = np.array([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y 

(array([ 3,  4,  6, 10]),
 array([-1,  0,  2,  6]),
 array([ 2,  4,  8, 16]),
 array([0.5, 1. , 2. , 4. ]),
 array([ 1,  4, 16, 64]))

In [15]:
np.exp(x)

array([2.71828183e+00, 7.38905610e+00, 5.45981500e+01, 2.98095799e+03])

In [17]:
x = np.arange(12).reshape(3, 4)
y = np.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
np.concatenate([x, y], axis = 0), np.concatenate([x, y], axis = 1)

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 2,  1,  4,  3],
        [ 1,  2,  3,  4],
        [ 4,  3,  2,  1]]),
 array([[ 0,  1,  2,  3,  2,  1,  4,  3],
        [ 4,  5,  6,  7,  1,  2,  3,  4],
        [ 8,  9, 10, 11,  4,  3,  2,  1]]))

In [18]:
x == y

array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [19]:
x.sum()

66

## **1.3. Broadcasting Mechanism**

In [20]:
a = np.arange(3).reshape(3, 1)
b = np.arange(2).reshape(1, 2)
a, b

(array([[0],
        [1],
        [2]]),
 array([[0, 1]]))

In [21]:
a + b

array([[0, 1],
       [1, 2],
       [2, 3]])

## **1.4. Array Access**

In [23]:
x[-1], x[1:3]

(array([ 8,  9, 10, 11]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]))

In [24]:
x[1, 2] = 9
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  9,  7],
       [ 8,  9, 10, 11]])

In [26]:
x[0:2, :] = 12
x

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [ 8,  9, 10, 11]])

## 1.5. Memory Saving

In [27]:
before = id(y)
y = y + x
before == id(y)

False

In [29]:
z = np.zeros_like(y)
print('id(z):', id(z))
z[:] = x + y
print('id(z):', id(z))

id(z): 140290997798432
id(z): 140290997798432
