# **3. Linear Algebra**

## ***3.1. Scalar***

In [1]:
import numpy as np

x = np.array(3.0)
y = np.array(2.0)

x+y, x-y, x*y, x/y, x**y

(5.0, 1.0, 6.0, 1.5, 9.0)

## ***3.2. Vector***

In [2]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [3]:
x[3]

3

In [4]:
len(x)

4

In [5]:
x.shape

(4,)

In [6]:
x.size

4

In [7]:
x.sum()

6

## ***3.3. Matrix***

In [9]:
A = np.arange(20).reshape(5, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

### Transpose:

In [10]:
A.T

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

## 3.4. Tensor

In [12]:
X = np.arange(24).reshape(2, 3, 4)
X

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [14]:
B = A.copy()
A, A + B

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]]),
 array([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22],
        [24, 26, 28, 30],
        [32, 34, 36, 38]]))

In [15]:
A * B

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225],
       [256, 289, 324, 361]])

In [16]:
a = 2
a + A, (a*A).shape

(array([[ 2,  3,  4,  5],
        [ 6,  7,  8,  9],
        [10, 11, 12, 13],
        [14, 15, 16, 17],
        [18, 19, 20, 21]]),
 (5, 4))

## 3.5. Simplify

In [17]:
x = np.arange(4)
x, x.sum()

(array([0, 1, 2, 3]), 6)

In [18]:
A.shape, A.sum()

((5, 4), 190)

In [19]:
A_sum_axis0 = A.sum(axis = 0)
A_sum_axis0

array([40, 45, 50, 55])

In [20]:
A_sum_axis1 = A.sum(axis = 1)
A_sum_axis1

array([ 6, 22, 38, 54, 70])

In [21]:
A.mean(), A.sum() / A.size

(9.5, 9.5)

In [23]:
A.mean(axis=0)

array([ 8.,  9., 10., 11.])

In [26]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A

array([[ 6],
       [22],
       [38],
       [54],
       [70]])

In [28]:
A / sum_A

array([[0.        , 0.16666667, 0.33333333, 0.5       ],
       [0.18181818, 0.22727273, 0.27272727, 0.31818182],
       [0.21052632, 0.23684211, 0.26315789, 0.28947368],
       [0.22222222, 0.24074074, 0.25925926, 0.27777778],
       [0.22857143, 0.24285714, 0.25714286, 0.27142857]])

In [29]:
A.cumsum(axis = 0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21],
       [24, 28, 32, 36],
       [40, 45, 50, 55]])

## 3.6. Multiply Matrixes, vectors

In [30]:
y = np.ones(4)
x, y, np.dot(x, y)

(array([0, 1, 2, 3]), array([1., 1., 1., 1.]), 6.0)

In [31]:
A.shape, x.shape

((5, 4), (4,))

In [32]:
np.dot(A, x)

array([ 14,  38,  62,  86, 110])

In [33]:
B = np.ones(shape=(4, 3))
np.dot(A, B)

array([[ 6.,  6.,  6.],
       [22., 22., 22.],
       [38., 38., 38.],
       [54., 54., 54.],
       [70., 70., 70.]])

## 3.7. Norm

In [36]:
# l2 norm:
u = np.array([3, -4])
np.linalg.norm(u)

5.0

In [37]:
# l1 norm:
np.abs(u).sum()

7